version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ideageneration
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hKuOsu4wa1gH3VAdv8V
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    volumes:
      - ./:/app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: hKuOsu4wa1gH3VAdv8V
      DB_NAME: ideageneration
